### ISSUE TITLE
Re-establish Websocket Connection After Spec

### ISSUE THREAD

**Issue by chuck-adaptive** [zendesk/laika#39]
Hello, I'm enjoying Laika but am unable to run specs in the same window multiple times without a refresh when mocking WebSockets.

In http I -
* create interceptors
* run my spec
* `mockRestore` my interceptors & clean up
* Reusing that window - on to the next spec! Do the same, and my queries function as expected - I can pass in a new set, refetch the queries and the dom looks as I expect. 

With websockets I -
* create interceptors
* run my spec/`fireSubscriptionUpdate`
* `mockRestore` and cleanup? I've also tried doing nothing - not sure what I should/can do here
* *! am unable to to run the spec again in the same window* - `Cannot fire a subscription update as there is nothing listening to ....`

Is there a way to reset the mocks in a websocket connection? Or at the least, create a new interceptor to a previously intercepted websocket call

Thank you

**Comment by niieani** [comment]
As per documentation, `mockRestore` will only re-establish subscription-type connections for future connections, due to how Apollo works:

https://github.com/zendesk/laika/blob/bf91ff3bc2f3643d1bef9133d9b990d9416aebec/src/laika.ts#L956-L963

The reason is that the connection isn't being re-established. You would need to force your component to re-connect to the websocket.

If you want to mock the same connection multiple times, is there a reason for why you wouldn't just reuse the same interceptor that you setup once? i.e. create the interceptor in a variable inside of `beforeAll` and then use the same one in your tests (assuming a test scenario).

**Comment by chuck-adaptive** [comment]
It's the multi-scenario part that was getting tricky.

I see now that the active subscription is picked up from Apollo client. In my case, I wasn't re-establishing the connection on the client (attempting to re-use the same browser view)

Thank you for clarifying.
